[package]
name = "fold"
version = "0.1.0"
description = "Fold"
authors = ["you"]
edition = "2021"

[lib]
name = "fold_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-dialog = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-http = "2"
tauri-plugin-prevent-default = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portable-pty = "0.8"
window-vibrancy = "0.6"
reqwest = { version = "0.13.4", default-features = false, features = ["blocking", "rustls", "json"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
