/** Place-style workspace names, similar to Conductor's city naming. */
const PLACE_NAMES = [
  "amsterdam",
  "athens",
  "auckland",
  "baghdad",
  "bangkok",
  "barcelona",
  "beijing",
  "beirut",
  "berlin",
  "bogota",
  "boston",
  "brasilia",
  "brussels",
  "budapest",
  "buenos-aires",
  "cairo",
  "calgary",
  "canberra",
  "cape-town",
  "caracas",
  "casablanca",
  "chicago",
  "copenhagen",
  "dakar",
  "dallas",
  "delhi",
  "denver",
  "dhaka",
  "dublin",
  "edinburgh",
  "florence",
  "geneva",
  "hanoi",
  "havana",
  "helsinki",
  "hong-kong",
  "honolulu",
  "istanbul",
  "jakarta",
  "jerusalem",
  "johannesburg",
  "kabul",
  "karachi",
  "kathmandu",
  "kingston",
  "kinshasa",
  "kuwait",
  "kyiv",
  "lagos",
  "lima",
  "lisbon",
  "london",
  "madrid",
  "manila",
  "marrakech",
  "melbourne",
  "mexico-city",
  "miami",
  "milan",
  "montreal",
  "moscow",
  "mumbai",
  "munich",
  "nairobi",
  "naples",
  "new-york",
  "osaka",
  "oslo",
  "ottawa",
  "paris",
  "perth",
  "prague",
  "quebec",
  "quito",
  "reykjavik",
  "rio",
  "riyadh",
  "rome",
  "san-francisco",
  "santiago",
  "sao-paulo",
  "seoul",
  "shanghai",
  "singapore",
  "stockholm",
  "sydney",
  "taipei",
  "tokyo",
  "toronto",
  "vancouver",
  "venice",
  "vienna",
  "warsaw",
  "wellington",
  "zurich",
  "andorra",
  "bahrain",
  "bhutan",
  "botswana",
  "chile",
  "croatia",
  "cyprus",
  "ecuador",
  "estonia",
  "fiji",
  "georgia",
  "ghana",
  "iceland",
  "jordan",
  "kenya",
  "latvia",
  "luxembourg",
  "malta",
  "mongolia",
  "morocco",
  "nepal",
  "norway",
  "oman",
  "peru",
  "portugal",
  "qatar",
  "rwanda",
  "senegal",
  "slovenia",
  "tunisia",
  "uruguay",
  "zambia",
];

function shuffle<T>(items: T[]): T[] {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/**
 * Pick a unique place-style name not already used by existing worktrees.
 * Falls back to `name-<n>` if the pool is exhausted.
 */
export function pickWorktreeName(existing: string[]): string {
  const taken = new Set(existing.map((n) => n.toLowerCase()));
  for (const name of shuffle(PLACE_NAMES)) {
    if (!taken.has(name)) return name;
  }
  let n = 2;
  while (taken.has(`workspace-${n}`)) n += 1;
  return `workspace-${n}`;
}
