import type { TablerIcon } from "@tabler/icons-react";
import {
  IconArchive,
  IconBrandAngular,
  IconBrandAws,
  IconBrandAzure,
  IconBrandBlender,
  IconBrandCpp,
  IconBrandCSharp,
  IconBrandCss3,
  IconBrandDeno,
  IconBrandDocker,
  IconBrandFigma,
  IconBrandGit,
  IconBrandGolang,
  IconBrandGraphql,
  IconBrandHtml5,
  IconBrandJavascript,
  IconBrandKotlin,
  IconBrandLaravel,
  IconBrandNextjs,
  IconBrandNpm,
  IconBrandNuxt,
  IconBrandPhp,
  IconBrandPython,
  IconBrandReact,
  IconBrandRedux,
  IconBrandRust,
  IconBrandSolidjs,
  IconBrandSymfony,
  IconBrandSvelte,
  IconBrandSwift,
  IconBrandTerraform,
  IconBrandTypescript,
  IconBrandUnity,
  IconBrandVite,
  IconBrandVue,
  IconCoffee,
  IconCsv,
  IconDatabase,
  IconFile,
  IconFileCode,
  IconFileText,
  IconFolder,
  IconFolderCode,
  IconFolderOpen,
  IconJson,
  IconLock,
  IconMarkdown,
  IconMusic,
  IconPdf,
  IconPhoto,
  IconSettings,
  IconSql,
  IconSvg,
  IconTerminal,
  IconTex,
  IconToml,
  IconVideo,
} from "@tabler/icons-react";
import type { FileIconKind } from "./fileIconMap";

const ICON_MAP: Record<FileIconKind, TablerIcon> = {
  folder: IconFolder,
  "folder-open": IconFolderOpen,
  "folder-code": IconFolderCode,
  typescript: IconBrandTypescript,
  javascript: IconBrandJavascript,
  react: IconBrandReact,
  vue: IconBrandVue,
  svelte: IconBrandSvelte,
  angular: IconBrandAngular,
  python: IconBrandPython,
  rust: IconBrandRust,
  go: IconBrandGolang,
  csharp: IconBrandCSharp,
  cpp: IconBrandCpp,
  java: IconFileCode,
  kotlin: IconBrandKotlin,
  scala: IconFileCode,
  ruby: IconFileCode,
  swift: IconBrandSwift,
  php: IconBrandPhp,
  dart: IconFileCode,
  elixir: IconFileCode,
  html: IconBrandHtml5,
  css: IconBrandCss3,
  json: IconJson,
  yaml: IconSettings,
  toml: IconToml,
  markdown: IconMarkdown,
  sql: IconSql,
  shell: IconTerminal,
  docker: IconBrandDocker,
  terraform: IconBrandTerraform,
  graphql: IconBrandGraphql,
  node: IconBrandJavascript,
  npm: IconBrandNpm,
  next: IconBrandNextjs,
  nuxt: IconBrandNuxt,
  vite: IconBrandVite,
  deno: IconBrandDeno,
  solid: IconBrandSolidjs,
  laravel: IconBrandLaravel,
  symfony: IconBrandSymfony,
  redux: IconBrandRedux,
  aws: IconBrandAws,
  azure: IconBrandAzure,
  git: IconBrandGit,
  lock: IconLock,
  config: IconSettings,
  code: IconFileCode,
  text: IconFileText,
  xml: IconFileCode,
  svg: IconSvg,
  csv: IconCsv,
  pdf: IconPdf,
  image: IconPhoto,
  video: IconVideo,
  audio: IconMusic,
  archive: IconArchive,
  database: IconDatabase,
  figma: IconBrandFigma,
  blender: IconBrandBlender,
  unity: IconBrandUnity,
  coffee: IconCoffee,
  tex: IconTex,
  file: IconFile,
};

interface MonotoneFileIconProps {
  kind: FileIconKind;
  size?: number;
  className?: string;
}

export default function MonotoneFileIcon({
  kind,
  size = 16,
  className,
}: MonotoneFileIconProps) {
  const Icon = ICON_MAP[kind] ?? IconFile;

  return (
    <Icon
      size={size}
      stroke={1.5}
      className={className}
      aria-hidden="true"
    />
  );
}
